# Generated by Django 3.1.2 on 2021-07-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Pcs', 'Pcs'), ('Kgs', 'Kgs'), ('Gms', 'Gms')], max_length=5)),
                ('status', models.CharField(choices=[('Bought', 'Bought'), ('Left', 'Left'), ('Not-Available', 'Not-Available')], max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
